Update cloudbuild.yaml

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -2,7 +2,7 @@
 substitutions:
   _COMPOSER_REGION: asia-south1
   _COMPOSER_ENV_NAME: airflow-cicd
-  _ROLLBACK: 'True'
+  _ROLLBACK: 'False'
   _SEVERITY: MEDIUM
   _SEVERITY1: HIGH
   _SEVERITY2: CRITICAL
@@ -66,52 +66,52 @@ steps:
   - name: 'gcr.io/cloud-builders/docker'
     args: ['build', '-t', 'gcr.io/niveustraining/airflow-image-uat:v1.0', '.']
 
-#   - id: scan
-#     name: gcr.io/cloud-builders/gcloud
-#     entrypoint: /bin/bash
-#     args:
-#      - -c
-#      - |
-#        gcloud artifacts docker images scan 'gcr.io/niveustraining/airflow-image-uat:v1.0' \
-#        --format='value(response.scan)' > /workspace/docdags/scan_id.txt
+  - id: scan
+    name: gcr.io/cloud-builders/gcloud
+    entrypoint: /bin/bash
+    args:
+     - -c
+     - |
+       gcloud artifacts docker images scan 'gcr.io/niveustraining/airflow-image-uat:v1.0' \
+       --format='value(response.scan)' > /workspace/docdags/scan_id.txt
        
-#   - id: severity_Critical
-#     name: gcr.io/cloud-builders/gcloud
-#     entrypoint: /bin/bash
-#     args:
-#      - -c
-#      - | 
-#        gcloud artifacts docker images list-vulnerabilities \
-#         $(cat /workspace/docdags/scan_id.txt) --format='value(vulnerability.effectiveSeverity)' \
-#         | if grep -Fxq $_SEVERITY2 
-#           then echo 'Failed vulnerability check - CRITICAL'
-#           exit 1 
-#           fi
+  - id: severity_Critical
+    name: gcr.io/cloud-builders/gcloud
+    entrypoint: /bin/bash
+    args:
+     - -c
+     - | 
+       gcloud artifacts docker images list-vulnerabilities \
+        $(cat /workspace/docdags/scan_id.txt) --format='value(vulnerability.effectiveSeverity)' \
+        | if grep -Fxq $_SEVERITY2 
+          then echo 'Failed vulnerability check - CRITICAL'
+          exit 1 
+          fi
           
-#   - id: severity_High
-#     name: gcr.io/cloud-builders/gcloud
-#     entrypoint: /bin/bash
-#     args:
-#      - -c
-#      - | 
-#        gcloud artifacts docker images list-vulnerabilities \
-#         $(cat /workspace/docdags/scan_id.txt) --format='value(vulnerability.effectiveSeverity)' \
-#         | if grep -Fxq $_SEVERITY1
-#           then echo 'Failed vulnerability check - HIGH'
-#           exit 1 
-#           fi
-#   - id: severity_Medium
-#     name: gcr.io/cloud-builders/gcloud
-#     entrypoint: /bin/bash
-#     args:
-#      - -c
-#      - | 
-#        gcloud artifacts docker images list-vulnerabilities \
-#         $(cat /workspace/docdags/scan_id.txt) --format='value(vulnerability.effectiveSeverity)' \
-#         | if grep -Fxq $_SEVERITY 
-#           then echo 'Failed vulnerability check - MEDIUM'
-#           exit 1 
-#           fi
+  - id: severity_High
+    name: gcr.io/cloud-builders/gcloud
+    entrypoint: /bin/bash
+    args:
+     - -c
+     - | 
+       gcloud artifacts docker images list-vulnerabilities \
+        $(cat /workspace/docdags/scan_id.txt) --format='value(vulnerability.effectiveSeverity)' \
+        | if grep -Fxq $_SEVERITY1
+          then echo 'Failed vulnerability check - HIGH'
+          exit 1 
+          fi
+  - id: severity_Medium
+    name: gcr.io/cloud-builders/gcloud
+    entrypoint: /bin/bash
+    args:
+     - -c
+     - | 
+       gcloud artifacts docker images list-vulnerabilities \
+        $(cat /workspace/docdags/scan_id.txt) --format='value(vulnerability.effectiveSeverity)' \
+        | if grep -Fxq $_SEVERITY 
+          then echo 'Failed vulnerability check - MEDIUM'
+          exit 1 
+          fi
     
 # Push the image to GCR
   - name: 'gcr.io/cloud-builders/docker'
